version: 2102.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2019
environment:
  GitHubKey:
    secure: 085aq77wGuI+EI1wXVyiB8ERrsksUfSVrPjoxCzusqT8SFnY/Sb8P0PsKqvhybgF
  NuGetApiKey:
    secure: /YPozcX4yV1XCrZuS8DAhOmH/OOjkg6+zrCTT3lHR3a7/SY7S83JNNgYBsROlLq3
  Module: Evergreen
install:
- ps: . .\ci\Install.ps1
build_script:
- ps: . .\ci\Build.ps1
test_script:
- ps: . .\ci\Tests.ps1
deploy_script:
- ps: . .\ci\Deploy.ps1

skip_commits:
  message: /AppVeyor validate.*|Merge branch 'master' of.*/

only_commits:
  files:
    - Evergreen/**/*
